---
Exception\ConfigurationException:
  comment: |-
    ConfigurationException is raised when query is syntactically correct but
    invalid because of some configuration issue.
    For example when attempting to drop a non-existent keyspace.
  methods:
    __construct:
      comment: ""
      params:
        message:
          comment: ""
          type: string
        code:
          comment: ""
          type: int
        previous:
          comment: ""
          type: \Exception
    __wakeup:
      comment: ""
      return:
        comment: ""
        type: void
    __toString:
      comment: ""
      return:
        comment: ""
        type: string
...
